# Generated by Django 3.1.6 on 2021-02-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, unique=True, verbose_name='Eventname')),
                ('event_is_current', models.BooleanField(default=True, verbose_name='Aktuelles Event')),
                ('event_url_thread', models.CharField(max_length=200, verbose_name='Thread URL')),
                ('event_url_posting', models.CharField(max_length=200, verbose_name='Posting URL')),
            ],
        ),
    ]
