# Generated by Django 3.1.6 on 2021-02-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_album',
            field=models.CharField(default='leer', max_length=200, verbose_name='Album bei Imgur'),
            preserve_default=False,
        ),
    ]
