# Generated by Django 3.1.6 on 2021-02-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0002_event_event_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgur_access_token', models.CharField(max_length=200)),
                ('imgur_refresh_token', models.CharField(max_length=200)),
                ('current_login', models.BooleanField(default=False)),
            ],
        ),
    ]
