# Generated by Django 3.1.6 on 2021-02-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0003_imgur'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgur',
            name='pin',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
