# Generated by Django 3.1.6 on 2021-02-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0004_imgur_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgur',
            name='pin',
        ),
    ]
