# Generated by Django 3.1.6 on 2021-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0005_remove_imgur_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='Name der Plattform', max_length=200, unique=True)),
                ('platform_image', models.CharField(max_length=200)),
                ('PC', models.BooleanField(default=False)),
                ('Console', models.BooleanField(default=False)),
                ('VR', models.BooleanField(default=False)),
                ('Stream', models.BooleanField(default=False)),
            ],
        ),
    ]
