# Generated by Django 3.1.6 on 2021-02-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0006_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='Console',
            new_name='console',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='PC',
            new_name='pc',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='Stream',
            new_name='stream',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='VR',
            new_name='vr',
        ),
    ]
