# Generated by Django 3.1.6 on 2021-02-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0007_auto_20210223_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='console',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='pc',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='vr',
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
