# Generated by Django 3.1.6 on 2021-02-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0008_auto_20210223_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(help_text='Spieltitel', max_length=200, unique=True)),
                ('release_date', models.CharField(help_text='Release', max_length=200)),
                ('events', models.ManyToManyField(to='bbcapi.Event')),
                ('platforms', models.ManyToManyField(help_text='Spiel', to='bbcapi.Platform')),
            ],
        ),
    ]
