# Generated by Django 3.1.6 on 2021-02-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0009_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='events',
            new_name='game_events',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='platforms',
            new_name='game_platforms',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='game_release_date',
        ),
    ]
