# Generated by Django 3.1.6 on 2021-02-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0010_auto_20210223_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_platforms',
            field=models.ManyToManyField(help_text='Spiel', related_name='games', to='bbcapi.Platform'),
        ),
    ]
