# Generated by Django 3.1.6 on 2021-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0011_auto_20210228_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_platforms',
            field=models.ManyToManyField(help_text='Spiel', to='bbcapi.Platform'),
        ),
    ]
