# Generated by Django 3.1.6 on 2021-03-01 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0012_auto_20210228_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_url', models.CharField(help_text='Trailer URL', max_length=200)),
                ('trailer_name', models.CharField(help_text='Trailer Name', max_length=200)),
                ('trailer_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbcapi.game')),
            ],
        ),
    ]
