# Generated by Django 3.1.6 on 2021-03-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0013_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_trailers', to='bbcapi.game'),
        ),
    ]
