# Generated by Django 3.1.6 on 2021-03-04 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0014_auto_20210301_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyart_url', models.CharField(help_text='Keyart', max_length=200)),
                ('keyart_name', models.CharField(help_text='Keyart des Spiels', max_length=200, unique=True)),
                ('dummy_keyartYesNo', models.BooleanField(default=True)),
                ('game_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_game', to='bbcapi.game')),
            ],
        ),
    ]
