# Generated by Django 3.1.6 on 2021-03-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0015_keyart'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_keyart',
            field=models.CharField(default='', help_text='Keyart', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Keyart',
        ),
    ]
