# Generated by Django 3.1.6 on 2021-03-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0017_auto_20210304_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_keyart',
        ),
    ]
