# Generated by Django 3.1.6 on 2021-03-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0018_remove_game_game_keyart'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_keyart',
            field=models.CharField(default='https://i.imgur.com/9krYg4n.png', help_text='Keyart', max_length=200),
        ),
    ]
