# Generated by Django 3.1.6 on 2021-03-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0019_game_game_keyart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_release_date',
            field=models.CharField(default='TBA', help_text='Release', max_length=200),
        ),
    ]
