# Generated by Django 3.1.6 on 2021-03-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0020_auto_20210305_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_name']},
        ),
    ]
