# Generated by Django 3.1.6 on 2021-03-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0021_auto_20210305_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['-trailer_date']},
        ),
    ]
