# Generated by Django 3.1.6 on 2021-03-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0022_auto_20210305_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['platform_type', 'platform_name']},
        ),
    ]
