# Generated by Django 3.1.6 on 2021-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0023_auto_20210305_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='DeltaYesNo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trailer',
            name='DeltaYesNo',
            field=models.BooleanField(default=False),
        ),
    ]
