# Generated by Django 3.1.6 on 2021-03-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0024_auto_20210305_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_trailers', to='bbcapi.game'),
        ),
    ]
