# Generated by Django 3.1.6 on 2021-03-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0025_auto_20210306_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='game_production',
            field=models.CharField(default='', max_length=200),
        ),
    ]
