# Generated by Django 3.1.6 on 2021-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0026_auto_20210307_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_needs_update',
            field=models.BooleanField(default=True),
        ),
    ]
