# Generated by Django 3.1.6 on 2021-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0028_game_game_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_hidden_games', models.BooleanField(default=True)),
            ],
        ),
    ]
