# Generated by Django 3.1.6 on 2021-04-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbcapi', '0029_base'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='BaseData',
        ),
    ]
